/**
 * Üreteç şemaları — §4.1.
 *
 * Sıra editörde de bu sırayla görünür: sabit, gradyanlar, gürültü, işaretli
 * mesafe alanları, desenler.
 */

import type { NodeSchema } from './types';
import { CENTER_PARAM, SEED_PARAM, SIGNED, UNIT, freqParam } from './types';

export const GENERATOR_SCHEMAS: readonly NodeSchema[] = [
  {
    kind: 'const',
    category: 'generator',
    output: UNIT,
    description: 'Sabit alan; maske ve karışım için taban.',
    params: [
      {
        name: 'value',
        type: 'number',
        range: [0, 1],
        step: 0.01,
        default: 1,
        description: 'Her noktada dönen değer.',
      },
    ],
  },
  {
    kind: 'gradient.linear',
    category: 'generator',
    output: UNIT,
    description: 'Bir eksen boyunca 0→1 rampası.',
    params: [
      {
        name: 'angle',
        type: 'number',
        range: [-180, 180],
        step: 1,
        default: 0,
        description: 'Rampanın yönü, DERECE.',
      },
      {
        name: 'from',
        type: 'number',
        range: [-2, 2],
        step: 0.01,
        default: -1,
        description: 'Rampanın 0 olduğu birim-uzay konumu.',
      },
      {
        name: 'to',
        type: 'number',
        range: [-2, 2],
        step: 0.01,
        default: 1,
        description: 'Rampanın 1 olduğu birim-uzay konumu.',
      },
    ],
  },
  {
    kind: 'gradient.radial',
    category: 'generator',
    output: UNIT,
    description: 'Merkezde 1, yarıçapta 0 olan dairesel rampa; hacim tabanı.',
    params: [
      CENTER_PARAM,
      {
        name: 'radius',
        type: 'number',
        range: [0.01, 2],
        step: 0.01,
        default: 1,
        constraint: 'positive',
        description: 'Rampanın sıfıra indiği uzaklık.',
      },
    ],
  },
  {
    kind: 'gradient.angular',
    category: 'generator',
    output: UNIT,
    description: 'Merkez etrafında bir tam turda 0→1; dişli ve pasta dilimi için.',
    params: [
      CENTER_PARAM,
      {
        name: 'offset',
        type: 'number',
        range: [-180, 180],
        step: 1,
        default: 0,
        optional: true,
        description: 'Başlangıç açısı, DERECE.',
      },
    ],
  },
  {
    kind: 'gradient.diamond',
    category: 'generator',
    output: UNIT,
    description: 'Manhattan uzaklığı: merkezde 1, `size` uzaklığında 0.',
    params: [
      CENTER_PARAM,
      {
        name: 'size',
        type: 'number',
        range: [0.01, 2],
        step: 0.01,
        default: 1,
        constraint: 'positive',
        description: 'Rampanın sıfıra indiği Manhattan uzaklığı.',
      },
    ],
  },
  {
    kind: 'noise.value',
    category: 'generator',
    output: UNIT,
    description: 'Kafes tabanlı değer gürültüsü; en ucuz gürültü, blok karakterli.',
    params: [freqParam(8), SEED_PARAM],
  },
  {
    kind: 'noise.simplex',
    category: 'generator',
    output: UNIT,
    description: 'Eğik kafes gürültüsü; eksen yapaylığı düşük. Döşenebilir belgede kullanılamaz.',
    params: [freqParam(8), SEED_PARAM],
  },
  {
    kind: 'noise.worley',
    category: 'generator',
    output: UNIT,
    description: 'Hücresel gürültü; `F2-F1` hücre kenarlarını verir.',
    params: [
      freqParam(6),
      {
        name: 'mode',
        type: 'enum',
        options: ['F1', 'F2', 'F2-F1'],
        default: 'F1',
        optional: true,
        description: 'Hangi öznitelik uzaklığı okunur.',
      },
      SEED_PARAM,
    ],
  },
  {
    kind: 'noise.fbm',
    category: 'generator',
    output: UNIT,
    description: 'Oktav toplayıcı sarmalayıcı; oktavlar arasında döndürme uygular (§5.1).',
    params: [
      {
        name: 'base',
        type: 'field',
        description: 'Toplanacak BİRİM alan; genellikle bir gürültü.',
      },
      {
        name: 'octaves',
        type: 'int',
        range: [1, 8],
        // Her oktav piksel başına ek bir gürültü örneklemesi demektir;
        // sınırsız bırakılırsa render süresi lineer değil pratikte sonsuza
        // gider. Sanatsal `range` 8'de kalsa da tavan çok daha cömert.
        hardMax: 64,
        step: 1,
        default: 4,
        constraint: 'positive',
        description: 'Kaç ölçekte toplanacağı.',
      },
      {
        name: 'lacunarity',
        type: 'number',
        range: [1.1, 4],
        step: 0.1,
        default: 2,
        optional: true,
        constraint: 'positive',
        description: 'Oktav başına frekans çarpanı. Döşenebilir belgede TAM SAYI olmalı.',
      },
      {
        name: 'gain',
        type: 'number',
        range: [0.1, 0.9],
        step: 0.05,
        default: 0.5,
        optional: true,
        constraint: 'positive',
        description: 'Oktav başına genlik çarpanı.',
      },
    ],
  },
  {
    kind: 'sdf.circle',
    category: 'generator',
    output: SIGNED,
    description: 'Daire işaretli mesafesi; negatif içeridedir.',
    params: [
      CENTER_PARAM,
      {
        name: 'r',
        type: 'number',
        range: [0.01, 2],
        step: 0.01,
        default: 0.5,
        constraint: 'positive',
        description: 'Yarıçap.',
      },
    ],
  },
  {
    kind: 'sdf.box',
    category: 'generator',
    output: SIGNED,
    description: 'Kutu işaretli mesafesi; negatif içeridedir.',
    params: [
      CENTER_PARAM,
      {
        name: 'half',
        type: 'vec2',
        range: [0, 2],
        step: 0.01,
        default: [0.5, 0.5],
        constraint: 'nonNegative',
        description: 'Yarım kenar uzunlukları.',
      },
    ],
  },
  {
    kind: 'sdf.roundBox',
    category: 'generator',
    output: SIGNED,
    description: 'Köşesi yuvarlatılmış kutu; `sdf.box`tan türetilemez, ayrı formül.',
    params: [
      CENTER_PARAM,
      {
        name: 'half',
        type: 'vec2',
        range: [0, 2],
        step: 0.01,
        default: [0.5, 0.5],
        constraint: 'nonNegative',
        description: 'Yarım kenar uzunlukları.',
      },
      {
        name: 'r',
        type: 'number',
        range: [0, 1],
        step: 0.01,
        default: 0.1,
        constraint: 'nonNegative',
        description: 'Köşe yuvarlama yarıçapı.',
      },
    ],
  },
  {
    kind: 'sdf.polygon',
    category: 'generator',
    output: SIGNED,
    description: 'Düzgün n-gen; `r` çevrel yarıçaptır.',
    params: [
      CENTER_PARAM,
      {
        name: 'n',
        type: 'int',
        range: [3, 16],
        step: 1,
        default: 6,
        constraint: 'atLeastThree',
        description: 'Kenar sayısı.',
      },
      {
        name: 'r',
        type: 'number',
        range: [0.01, 2],
        step: 0.01,
        default: 0.5,
        constraint: 'positive',
        description: 'Çevrel yarıçap.',
      },
      {
        name: 'rotation',
        type: 'number',
        range: [-180, 180],
        step: 1,
        default: 0,
        optional: true,
        description: 'Dönme açısı, DERECE.',
      },
    ],
  },
  {
    kind: 'sdf.star',
    category: 'generator',
    output: SIGNED,
    description: 'n uçlu yıldız.',
    params: [
      CENTER_PARAM,
      {
        name: 'n',
        type: 'int',
        range: [3, 16],
        step: 1,
        default: 5,
        constraint: 'atLeastThree',
        description: 'Uç sayısı.',
      },
      {
        name: 'rOuter',
        type: 'number',
        range: [0.01, 2],
        step: 0.01,
        default: 0.5,
        constraint: 'positive',
        description: 'Dış yarıçap.',
      },
      {
        name: 'rInner',
        type: 'number',
        range: [0.01, 2],
        step: 0.01,
        default: 0.22,
        constraint: 'positive',
        description: 'İç yarıçap.',
      },
      {
        name: 'rotation',
        type: 'number',
        range: [-180, 180],
        step: 1,
        default: 0,
        optional: true,
        description: 'Dönme açısı, DERECE.',
      },
    ],
  },
  {
    kind: 'sdf.line',
    category: 'generator',
    output: SIGNED,
    description: 'Kalın doğru parçası; uçları DÜZ.',
    params: [
      {
        name: 'a',
        type: 'vec2',
        range: [-2, 2],
        step: 0.01,
        default: [-0.5, 0],
        description: 'Başlangıç noktası.',
      },
      {
        name: 'b',
        type: 'vec2',
        range: [-2, 2],
        step: 0.01,
        default: [0.5, 0],
        description: 'Bitiş noktası.',
      },
      {
        name: 'thickness',
        type: 'number',
        range: [0.005, 1],
        step: 0.005,
        default: 0.1,
        constraint: 'positive',
        description: 'Toplam kalınlık.',
      },
    ],
  },
  {
    kind: 'sdf.capsule',
    category: 'generator',
    output: SIGNED,
    description: 'Uçları YUVARLAK kapsül; gövde ve dal için temel.',
    params: [
      {
        name: 'a',
        type: 'vec2',
        range: [-2, 2],
        step: 0.01,
        default: [0, -0.4],
        description: 'Başlangıç noktası.',
      },
      {
        name: 'b',
        type: 'vec2',
        range: [-2, 2],
        step: 0.01,
        default: [0, 0.4],
        description: 'Bitiş noktası.',
      },
      {
        name: 'r',
        type: 'number',
        range: [0.005, 1],
        step: 0.005,
        default: 0.12,
        constraint: 'positive',
        description: 'Yarıçap.',
      },
    ],
  },
  {
    kind: 'sdf.arc',
    category: 'generator',
    output: SIGNED,
    description: 'Halka dilimi.',
    params: [
      CENTER_PARAM,
      {
        name: 'r',
        type: 'number',
        range: [0.01, 2],
        step: 0.01,
        default: 0.5,
        constraint: 'positive',
        description: 'Halka yarıçapı.',
      },
      {
        name: 'thickness',
        type: 'number',
        range: [0.005, 1],
        step: 0.005,
        default: 0.1,
        constraint: 'positive',
        description: 'Halka kalınlığı.',
      },
      {
        name: 'from',
        type: 'number',
        range: [-360, 360],
        step: 1,
        default: 0,
        description: 'Başlangıç açısı, DERECE.',
      },
      {
        name: 'to',
        type: 'number',
        range: [-360, 360],
        step: 1,
        default: 180,
        description: 'Bitiş açısı, DERECE.',
      },
    ],
  },
  {
    kind: 'sdf.path',
    category: 'generator',
    output: SIGNED,
    description: 'Capsule segmentlerinden oluşan kalın yol; kablo, sap, damar ve dal için.',
    params: [
      {
        name: 'points',
        type: 'points',
        range: [-2, 2],
        step: 0.01,
        default: [
          [-0.5, 0],
          [0, 0.35],
          [0.5, 0],
        ],
        description: 'En az iki `[x, y]` yol noktası; ardışık noktalar capsule ile bağlanır.',
      },
      {
        name: 'r',
        type: 'number',
        range: [0.005, 1],
        step: 0.005,
        default: 0.08,
        constraint: 'positive',
        description: 'Yol kalınlığının yarıçapı.',
      },
      {
        name: 'closed',
        type: 'bool',
        default: false,
        optional: true,
        description: 'Doğruysa son noktayı ilk noktaya bağlar.',
      },
    ],
  },
  {
    kind: 'pattern.checker',
    category: 'generator',
    output: UNIT,
    description: 'Dama deseni.',
    params: [
      {
        name: 'size',
        type: 'number',
        range: [0.01, 1],
        step: 0.01,
        default: 0.25,
        constraint: 'positive',
        description: 'Bir karenin birim uzaydaki kenarı.',
      },
    ],
  },
  {
    kind: 'pattern.stripes',
    category: 'generator',
    output: UNIT,
    description: 'Çizgiler.',
    params: [
      freqParam(8),
      {
        name: 'angle',
        type: 'number',
        range: [-180, 180],
        step: 1,
        default: 0,
        optional: true,
        description: 'Çizgi yönü, DERECE.',
      },
      {
        name: 'duty',
        type: 'number',
        range: [0, 1],
        step: 0.05,
        default: 0.5,
        optional: true,
        constraint: 'unit',
        description: 'Dolu kısmın periyoda oranı.',
      },
    ],
  },
  {
    kind: 'pattern.dots',
    category: 'generator',
    output: UNIT,
    description: 'Noktalar.',
    params: [
      freqParam(8),
      {
        name: 'r',
        type: 'number',
        range: [0, 1.4],
        step: 0.05,
        default: 0.5,
        constraint: 'nonNegative',
        description: 'Nokta yarıçapının hücre yarı genişliğine oranı.',
      },
    ],
  },
  {
    kind: 'pattern.grid',
    category: 'generator',
    output: UNIT,
    description: 'Izgara çizgileri.',
    params: [
      freqParam(8),
      {
        name: 'thickness',
        type: 'number',
        range: [0, 1],
        step: 0.02,
        default: 0.1,
        constraint: 'unit',
        description: 'Çizgi kalınlığının hücre genişliğine oranı.',
      },
    ],
  },
  {
    kind: 'pattern.hex',
    category: 'generator',
    output: UNIT,
    description: 'Altıgen döşeme; hücre merkezinde 1, kenarında 0.',
    params: [freqParam(6)],
  },
];
