packages:
  - 'core'
  - 'devtools/*'
  - 'games/*'
  - 'tauri-v2'
publicHoistPattern:
  - '@tauri-apps/*'
overrides:
  colord: 2.10.0
  js-yaml: 4.3.2
allowBuilds:
  esbuild: true
  simple-git-hooks: true
