packages:
  - 'core'
  - 'devtools/*'
  - 'games/*'
  - 'tauri-v2'
publicHoistPattern:
  - '@tauri-apps/*'
allowBuilds:
  esbuild: true
  just-install: true
  simple-git-hooks: true
patchedDependencies:
  vitest@3.2.6: patches/vitest@3.2.6.patch
