import type { PresetMetadata } from '../types';

export const COMBAT_CATALOG: Record<string, PresetMetadata> = {
  fire: {
    category: 'combat',
    genre: 'realistic',
    description: 'Yumuşak ateş / silah sesi, sine + pink noise.',
    typicalFrequency: 420,
    typicalDuration: 0.12,
    useCase: 'Projectile fire, soft gun shot',
    tags: ['weapon', 'fire', 'soft', 'pink-noise'],
    related: ['laser', 'bulletBounce'],
  },
  bulletBounce: {
    category: 'combat',
    genre: 'realistic',
    description: 'Mermi zıplama / sekmesi sesi.',
    typicalFrequency: 320,
    typicalDuration: 0.15,
    useCase: 'Bullet bounce, ricochet',
    tags: ['ricochet', 'bounce', 'short'],
    related: ['fire', 'hit'],
  },
  laser: {
    category: 'combat',
    genre: 'sci-fi',
    description: 'Hızlı frekans düşüşlü enerji / lazer silahı sesi.',
    typicalFrequency: 880,
    typicalDuration: 0.15,
    useCase: 'Projectile fire, sci-fi weapons, energy beams',
    tags: ['weapon', 'projectile', 'high-pitch', 'exponential-slide'],
    related: ['explosion', 'hit'],
  },
  explosion: {
    category: 'combat',
    genre: 'realistic',
    description: 'Geniş bant gürültü tabanlı patlama sesi.',
    typicalFrequency: 100,
    typicalDuration: 0.35,
    useCase: 'Explosions, destruction, heavy impacts',
    tags: ['impact', 'noise', 'low-end'],
    related: ['laser', 'hit'],
  },
  hit: {
    category: 'combat',
    genre: 'retro',
    description: 'Kısa ve keskin vuruş / darbe sesi.',
    typicalFrequency: 600,
    typicalDuration: 0.08,
    useCase: 'Enemy hit, melee impact, collision',
    tags: ['impact', 'short', 'sharp'],
    related: ['hurt', 'laser'],
  },
  hurt: {
    category: 'combat',
    genre: 'realistic',
    description: 'Hasar alma / yaralanma sesi.',
    typicalFrequency: 140,
    typicalDuration: 0.22,
    useCase: 'Player or enemy taking damage',
    tags: ['damage', 'grunt', 'low'],
    related: ['death', 'hit'],
  },
  death: {
    category: 'combat',
    genre: 'realistic',
    description: 'Ölüm / yenilgi sesi, sentez + gürültü katmanlı.',
    typicalFrequency: 220,
    typicalDuration: 0.7,
    useCase: 'Player or enemy death',
    tags: ['death', 'fail', 'long', 'noise'],
    related: ['hurt', 'explosion'],
  },
};
