import type { PresetMetadata } from '../types';

export const FM_CATALOG: Record<string, PresetMetadata> = {
  bell: {
    category: 'instrument',
    role: 'bell',
    genre: 'fantasy',
    description: 'FM zil sesi.',
    typicalFrequency: 440,
    typicalDuration: 0.6,
    useCase: 'Bell, item shine, magical ding',
    tags: ['fm', 'bell', 'metallic'],
    related: ['crystalBell', 'electricPiano', 'metallicClang'],
  },
  electricPiano: {
    category: 'instrument',
    role: 'keys',
    genre: 'retro',
    description: 'FM elektrik piyano / rhodes tarzı (yumuşatılmış).',
    typicalFrequency: 440,
    typicalDuration: 0.5,
    useCase: 'Piano stabs, level-up melody, chords',
    tags: ['fm', 'piano', 'warm', 'keys'],
    related: ['warmKeys', 'electricPiano2', 'bell'],
  },
  metallicClang: {
    category: 'instrument',
    role: 'percussion',
    genre: 'sci-fi',
    description: 'FM metalik vuruş / clang sesi.',
    typicalFrequency: 800,
    typicalDuration: 0.25,
    useCase: 'Shield hit, metal impact, energy clang',
    tags: ['fm', 'metallic', 'impact', 'percussion'],
    related: ['bell', 'metalPluck', 'fmLaser'],
  },
  dubBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'sci-fi',
    description: 'FM dub bas / growl.',
    typicalFrequency: 80,
    typicalDuration: 0.4,
    useCase: 'Enemy engine, robot move, bass growl',
    tags: ['fm', 'bass', 'growl'],
    related: ['subBass', 'pluckSubBass', 'fmLaser'],
  },
  fmLaser: {
    category: 'combat',
    genre: 'sci-fi',
    description: 'FM retro laser (agresif varyant).',
    typicalFrequency: 880,
    typicalDuration: 0.15,
    useCase: 'Sci-fi weapon, charged shot',
    tags: ['fm', 'laser', 'weapon'],
    related: ['laser', 'metallicClang'],
  },
};
