import type { PresetCategory, PresetGenre, PresetMetadata, InstrumentRole } from './types';

/** Tüm presetlerin keşfedilebilir metadata kataloğu. */
export const PRESET_CATALOG: Record<string, PresetMetadata> = {
  // combat
  fire: {
    category: 'combat',
    genre: 'realistic',
    description: 'Yumuşak ateş / silah sesi, sine + pink noise.',
    typicalFrequency: 420,
    typicalDuration: 0.12,
    useCase: 'Projectile fire, soft gun shot',
    tags: ['weapon', 'fire', 'soft', 'pink-noise'],
    related: ['laser', 'bulletBounce'],
  },
  bulletBounce: {
    category: 'combat',
    genre: 'realistic',
    description: 'Mermi zıplama / sekmesi sesi.',
    typicalFrequency: 320,
    typicalDuration: 0.15,
    useCase: 'Bullet bounce, ricochet',
    tags: ['ricochet', 'bounce', 'short'],
    related: ['fire', 'hit'],
  },
  laser: {
    category: 'combat',
    genre: 'sci-fi',
    description: 'Hızlı frekans düşüşlü enerji / lazer silahı sesi.',
    typicalFrequency: 880,
    typicalDuration: 0.15,
    useCase: 'Projectile fire, sci-fi weapons, energy beams',
    tags: ['weapon', 'projectile', 'high-pitch', 'exponential-slide'],
    related: ['explosion', 'hit'],
  },
  explosion: {
    category: 'combat',
    genre: 'realistic',
    description: 'Geniş bant gürültü tabanlı patlama sesi.',
    typicalFrequency: 100,
    typicalDuration: 0.35,
    useCase: 'Explosions, destruction, heavy impacts',
    tags: ['impact', 'noise', 'low-end'],
    related: ['laser', 'hit'],
  },
  hit: {
    category: 'combat',
    genre: 'retro',
    description: 'Kısa ve keskin vuruş / darbe sesi.',
    typicalFrequency: 600,
    typicalDuration: 0.08,
    useCase: 'Enemy hit, melee impact, collision',
    tags: ['impact', 'short', 'sharp'],
    related: ['hurt', 'laser'],
  },
  hurt: {
    category: 'combat',
    genre: 'realistic',
    description: 'Hasar alma / yaralanma sesi.',
    typicalFrequency: 140,
    typicalDuration: 0.22,
    useCase: 'Player or enemy taking damage',
    tags: ['damage', 'grunt', 'low'],
    related: ['death', 'hit'],
  },
  death: {
    category: 'combat',
    genre: 'realistic',
    description: 'Ölüm / yenilgi sesi, sentez + gürültü katmanlı.',
    typicalFrequency: 220,
    typicalDuration: 0.7,
    useCase: 'Player or enemy death',
    tags: ['death', 'fail', 'long', 'noise'],
    related: ['hurt', 'explosion'],
  },

  // ui
  blip: {
    category: 'ui',
    genre: 'retro',
    description: 'Kısa ve tiz menü / buton tık sesi.',
    typicalFrequency: 1200,
    typicalDuration: 0.06,
    useCase: 'Menu hover, button click, confirm blip',
    tags: ['ui', 'short', 'high-pitch'],
  },
  pause: {
    category: 'ui',
    genre: 'retro',
    description: 'Menüyü duraklatma sesi (aşağı kaymalı).',
    typicalFrequency: 320,
    typicalDuration: 0.22,
    useCase: 'Pause menu, slow down',
    tags: ['ui', 'pause', 'downward'],
    related: ['resume'],
  },
  resume: {
    category: 'ui',
    genre: 'retro',
    description: 'Oyuna devam etme sesi (yukarı kaymalı).',
    typicalFrequency: 120,
    typicalDuration: 0.22,
    useCase: 'Resume game, speed up',
    tags: ['ui', 'resume', 'upward'],
    related: ['pause'],
  },
  restart: {
    category: 'ui',
    genre: 'retro',
    description: 'Yeniden başlatma sesi (yukarı frekans kaymalı, detuned).',
    typicalFrequency: 440,
    typicalDuration: 0.18,
    useCase: 'Restart level, try again',
    tags: ['ui', 'restart', 'detuned'],
  },

  // movement
  jump: {
    category: 'movement',
    genre: 'retro',
    description: 'Yukarı doğru frekans kaymalı zıplama sesi.',
    typicalFrequency: 250,
    typicalDuration: 0.2,
    useCase: 'Player jump, bounce',
    tags: ['jump', 'upward', 'short'],
    related: ['dash', 'whoosh'],
  },
  dash: {
    category: 'movement',
    genre: 'sci-fi',
    description: 'Hızlı sürüklenme / dash sesi.',
    typicalFrequency: 800,
    typicalDuration: 0.2,
    useCase: 'Dash, dodge, quick movement',
    tags: ['dash', 'fast', 'sweep'],
    related: ['whoosh', 'jump'],
  },
  whoosh: {
    category: 'movement',
    genre: 'fantasy',
    description: 'Hızlı geçiş / hava kesme sesi.',
    typicalFrequency: 600,
    typicalDuration: 0.25,
    useCase: 'Swipe, melee swing, fast pass-by',
    tags: ['swoosh', 'swing', 'air'],
    related: ['dash', 'jump'],
  },

  // rewards
  coin: {
    category: 'reward',
    genre: 'retro',
    description: 'Kısa zıplamalı coin / puan toplama sesi.',
    typicalFrequency: 987,
    typicalDuration: 0.12,
    useCase: 'Collect coin, score pickup',
    tags: ['collectible', 'reward', 'high-pitch'],
    related: ['powerup'],
  },
  powerup: {
    category: 'reward',
    genre: 'sci-fi',
    description: 'Yukarı frekans kaymalı güç kazanma sesi.',
    typicalFrequency: 440,
    typicalDuration: 0.3,
    useCase: 'Power-up, ability unlock, positive feedback',
    tags: ['reward', 'power-up', 'upward'],
    related: ['coin'],
  },

  // fm (also instruments where appropriate)
  bell: {
    category: 'instrument',
    role: 'bell',
    genre: 'fantasy',
    description: 'FM zil sesi.',
    typicalFrequency: 440,
    typicalDuration: 0.6,
    useCase: 'Bell, item shine, magical ding',
    tags: ['fm', 'bell', 'metallic'],
    related: ['crystalBell', 'electricPiano', 'metallicClang'],
  },
  electricPiano: {
    category: 'instrument',
    role: 'keys',
    genre: 'retro',
    description: 'FM elektrik piyano / rhodes tarzı (yumuşatılmış).',
    typicalFrequency: 440,
    typicalDuration: 0.5,
    useCase: 'Piano stabs, level-up melody, chords',
    tags: ['fm', 'piano', 'warm', 'keys'],
    related: ['warmKeys', 'electricPiano2', 'bell'],
  },
  metallicClang: {
    category: 'instrument',
    role: 'percussion',
    genre: 'sci-fi',
    description: 'FM metalik vuruş / clang sesi.',
    typicalFrequency: 800,
    typicalDuration: 0.25,
    useCase: 'Shield hit, metal impact, energy clang',
    tags: ['fm', 'metallic', 'impact', 'percussion'],
    related: ['bell', 'metalPluck', 'fmLaser'],
  },
  dubBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'sci-fi',
    description: 'FM dub bas / growl.',
    typicalFrequency: 80,
    typicalDuration: 0.4,
    useCase: 'Enemy engine, robot move, bass growl',
    tags: ['fm', 'bass', 'growl'],
    related: ['subBass', 'pluckSubBass', 'fmLaser'],
  },
  fmLaser: {
    category: 'combat',
    genre: 'sci-fi',
    description: 'FM retro laser (agresif varyant).',
    typicalFrequency: 880,
    typicalDuration: 0.15,
    useCase: 'Sci-fi weapon, charged shot',
    tags: ['fm', 'laser', 'weapon'],
    related: ['laser', 'metallicClang'],
  },

  // textures
  softWind: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Yumuşak, sine-tabanlı rüzgâr / nefes dokusu.',
    typicalFrequency: 400,
    typicalDuration: 3,
    useCase: 'Pastoral ambience background, warm wind bed',
    tags: ['texture', 'pastoral', 'wind', 'pad'],
    related: ['warmPad', 'distantChime'],
  },
  warmPad: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Sıcak organ/yaylı karakterli additive pad.',
    typicalFrequency: 220,
    typicalDuration: 2.5,
    useCase: 'Pastoral chord pad, warm drone, theme background',
    tags: ['texture', 'pastoral', 'pad', 'additive'],
    related: ['softWind', 'malletPluck'],
  },
  machineHum: {
    category: 'texture',
    role: 'texture',
    genre: 'sci-fi',
    description: 'Soğuk, detune sawtooth makine uğultusu.',
    typicalFrequency: 110,
    typicalDuration: 2.5,
    useCase: 'Industrial drone, reactor bed, mechanical ambience',
    tags: ['texture', 'industrial', 'drone', 'machine'],
    related: ['staticField', 'reactorHum'],
  },
  staticField: {
    category: 'texture',
    role: 'texture',
    genre: 'sci-fi',
    description: 'Geniş bant pembe/beyaz gürültü katmanı.',
    typicalFrequency: 2200,
    typicalDuration: 3,
    useCase: 'Industrial noise floor, distant machinery, tension bed',
    tags: ['texture', 'industrial', 'noise', 'static'],
    related: ['machineHum', 'softWind'],
  },
  malletPluck: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Kısa, sıcak mallet / ahşap vuruş dokusu.',
    typicalFrequency: 660,
    typicalDuration: 0.35,
    useCase: 'Pastoral arpeggio, soft accent, warm pluck',
    tags: ['texture', 'pastoral', 'pluck', 'mallet'],
    related: ['warmPad', 'distantChime'],
  },
  distantChime: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Uzak, yumuşak çan vurgusu.',
    typicalFrequency: 880,
    typicalDuration: 2,
    useCase: 'Pastoral bell accent, magical distant chime',
    tags: ['texture', 'pastoral', 'bell', 'chime'],
    related: ['malletPluck', 'warmPad'],
  },

  // instruments
  subBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'realistic',
    description: 'Subtractive sawtooth/square bass, hafif drive.',
    typicalFrequency: 55,
    typicalDuration: 0.6,
    useCase: 'Warm bass foundation, rock/electronic bass line',
    tags: ['bass', 'subtractive', 'warm'],
    related: ['pluckSubBass', 'dubBass', 'softBass'],
  },
  pluckSubBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'sci-fi',
    description: 'FM perküsif sub bass, kısa atak.',
    typicalFrequency: 55,
    typicalDuration: 0.45,
    useCase: 'Plucky low-end, rhythmic bass',
    tags: ['bass', 'fm', 'pluck'],
    related: ['subBass', 'dubBass'],
  },
  softBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'realistic',
    description: 'Sine + triangle warm sub bass, distortion yok.',
    typicalFrequency: 55,
    typicalDuration: 0.6,
    useCase: 'Warm acoustic-style bass, pastoral themes',
    tags: ['bass', 'subtractive', 'soft'],
    related: ['subBass', 'mossBass'],
  },
  additivePad: {
    category: 'instrument',
    role: 'pad',
    genre: 'fantasy',
    description: 'Additive sine pad — organ/yaylı karakter.',
    typicalFrequency: 220,
    typicalDuration: 2.5,
    useCase: 'Chord backing, warm drone, theme bed',
    tags: ['pad', 'additive', 'warm'],
    related: ['detunedPad', 'warmPad', 'sunlitPad'],
  },
  detunedPad: {
    category: 'instrument',
    role: 'pad',
    genre: 'fantasy',
    description: 'Detune sawtooth pad — geniş ve sürükleyici.',
    typicalFrequency: 220,
    typicalDuration: 2.5,
    useCase: 'Wide synth pad, ambient backing',
    tags: ['pad', 'subtractive', 'wide'],
    related: ['additivePad', 'warmPad'],
  },
  brightLead: {
    category: 'instrument',
    role: 'lead',
    genre: 'sci-fi',
    description: 'Parlak, keskin sawtooth lead.',
    typicalFrequency: 440,
    typicalDuration: 0.7,
    useCase: 'Melodic lead, prominent theme line',
    tags: ['lead', 'subtractive', 'bright'],
    related: ['softLead', 'metalPluck'],
  },
  softLead: {
    category: 'instrument',
    role: 'lead',
    genre: 'fantasy',
    description: 'Yumuşak analog lead — triangle + hafif FM.',
    typicalFrequency: 440,
    typicalDuration: 0.8,
    useCase: 'Gentle melody, solo theme',
    tags: ['lead', 'subtractive', 'soft', 'fm'],
    related: ['brightLead', 'woodPluck'],
  },
  metalPluck: {
    category: 'instrument',
    role: 'pluck',
    genre: 'sci-fi',
    description: 'Metalik pluck — kısa inharmonik FM.',
    typicalFrequency: 660,
    typicalDuration: 0.35,
    useCase: 'Arpeggio, sequencer accent',
    tags: ['pluck', 'fm', 'metallic'],
    related: ['woodPluck', 'metallicClang'],
  },
  woodPluck: {
    category: 'instrument',
    role: 'pluck',
    genre: 'fantasy',
    description: 'Sıcak ahşap pluck — additive harmonikler.',
    typicalFrequency: 440,
    typicalDuration: 0.4,
    useCase: 'Pastoral arpeggio, warm accent',
    tags: ['pluck', 'additive', 'wood'],
    related: ['metalPluck', 'malletPluck'],
  },
  warmKeys: {
    category: 'instrument',
    role: 'keys',
    genre: 'fantasy',
    description: 'Yumuşak keys / Rhodes tan daha az metalik, additive.',
    typicalFrequency: 440,
    typicalDuration: 0.6,
    useCase: 'Soft chord stabs, warm piano alternative',
    tags: ['keys', 'additive', 'warm'],
    related: ['electricPiano', 'electricPiano2'],
  },
  electricPiano2: {
    category: 'instrument',
    role: 'keys',
    genre: 'retro',
    description: 'FM elektrik piyano — daha az gıcık, yumuşak varyant.',
    typicalFrequency: 440,
    typicalDuration: 0.5,
    useCase: 'Rhodes-style stab, chord melody',
    tags: ['keys', 'fm', 'warm'],
    related: ['electricPiano', 'warmKeys'],
  },
  crystalBell: {
    category: 'instrument',
    role: 'bell',
    genre: 'fantasy',
    description: 'Kristal berraklığında çan — additive + FM.',
    typicalFrequency: 880,
    typicalDuration: 1.2,
    useCase: 'Magical bell, high sparkle',
    tags: ['bell', 'additive', 'fm'],
    related: ['bell', 'distantChime'],
  },
} as const;

export interface FindPresetsQuery {
  category?: PresetCategory;
  role?: InstrumentRole;
  genre?: PresetGenre;
  tags?: string[];
  minFrequency?: number;
  maxDuration?: number;
}

/** Katalog içinde preset arar. */
export function findPresets(query: FindPresetsQuery = {}): string[] {
  return Object.entries(PRESET_CATALOG)
    .filter(([, meta]) => {
      if (query.category && meta.category !== query.category) return false;
      if (query.role && meta.role !== query.role) return false;
      if (query.genre && meta.genre !== query.genre) return false;
      if (query.tags && !query.tags.some((t) => meta.tags.includes(t))) return false;
      if (query.minFrequency && meta.typicalFrequency < query.minFrequency) return false;
      if (query.maxDuration && meta.typicalDuration > query.maxDuration) return false;
      return true;
    })
    .map(([name]) => name);
}
