import { describe, it, expect } from 'vitest';
import * as Core from '../../src/index';

/**
 * Public yüzeyin TAM isim listesi.
 *
 * Sayı bir BÜTÇEDİR, sözleşme değildir: bir isim silinip yerine başkası
 * eklendiğinde sayı değişmez ve kapı susar. Oysa o iki olay bir tüketici için
 * tamamen farklıdır — biri kırılma, diğeri genişleme.
 *
 * Liste alfabetiktir ve yüzeyden ÜRETİLİR; elle sıralanmaz. Düştüğünde hata
 * mesajı eklenen ve silinen adları AYRI AYRI gösterir, çünkü "223 → 223" bir
 * teşhis değildir.
 */
const EXPECTED_PUBLIC_SURFACE: readonly string[] = [
  'Accordion',
  'ActionBar',
  'ActionEdges',
  'AnimatedLabel',
  'AutosaveCoordinator',
  'Bar',
  'BaseSprite',
  'BuildMenu',
  'Button',
  'CARD_DRAG_MIME',
  'CanvasViewportController',
  'CardPicker',
  'CardTile',
  'Carousel',
  'ChargeButton',
  'Checkbox',
  'Clock',
  'ColorPicker',
  'CommandHistory',
  'CommandPalette',
  'CommandTransaction',
  'ConsoleTransport',
  'ContextMenu',
  'Cooldown',
  'Counter',
  'CursorController',
  'CurveEditor',
  'DEFAULT_MOVE_KEYS',
  'DEFAULT_SEED',
  'DEFAULT_UI_AUDIO_SETTINGS',
  'DEFAULT_UI_SOUND_PALETTE',
  'DENSITY_IDS',
  'DIAGONAL_NEIGHBOURS',
  'DPad',
  'DataTable',
  'Deck',
  'Diagnostics',
  'DialogueBox',
  'DirectionButton',
  'DisposableScope',
  'DualAxisScrollPanel',
  'Easing',
  'EventBus',
  'EventLog',
  'FOCUSABLE_SELECTOR',
  'FOCUS_NAV_CLASS',
  'FloatingTextManager',
  'FlowField',
  'FocusNavController',
  'FollowCamera',
  'FontManager',
  'FpsMeter',
  'FullscreenController',
  'GAMEPAD_BUTTON',
  'GAMEPAD_DEFAULT_DEAD_ZONE',
  'GamepadController',
  'GamepadPointerController',
  'GazeDriver',
  'GhostTrail',
  'Glyph',
  'GpuTimer',
  'GraphicsQuality',
  'Grid',
  'HIDE_ANIMATION_MS',
  'HoldButton',
  'I18n',
  'ICON_CATEGORIES',
  'INPUT',
  'Icon',
  'IconButton',
  'Input',
  'InputManager',
  'InputModeArbiter',
  'InputPresentationController',
  'InputStepBuffer',
  'InputUtils',
  'Joystick',
  'Kanban',
  'KeyBindingList',
  'KeyedVirtualList',
  'LEAVE_ANIMATION_MS',
  'LOADING_MIN_VISIBLE_MS',
  'LegGait',
  'LevelUpPicker',
  'LoadingScreen',
  'LocalServerTransport',
  'LocalStorageAdapter',
  'LongPressButton',
  'LoopBlend',
  'MOTION_BUDGET',
  'MOTION_DURATIONS',
  'MOTION_EASINGS',
  'MOTION_INTERACTION',
  'MOTION_PRESETS',
  'MinHeap',
  'MinimapPanel',
  'Modal',
  'MotionController',
  'MovableController',
  'MultiTouchZone',
  'Music',
  'MusicEngine',
  'MusicPlaylist',
  'NO_ACTIVE_PROVIDER',
  'NoopTransport',
  'NumberStepper',
  'ORTHOGONAL_NEIGHBOURS',
  'ObjectPool',
  'OnScreenKeyboard',
  'PCController',
  'PINCH_ZOOM',
  'Panel',
  'PathFinder',
  'PauseResumeButton',
  'PersistedObservableState',
  'PinchZoomController',
  'Popover',
  'Popup',
  'PoseShadow',
  'PropertyField',
  'PullToRefresh',
  'RETICLES',
  'RTS_CURSORS',
  'RadialMenu',
  'RadioGroup',
  'RangeSlider',
  'ResourceBar',
  'ResourceCounter',
  'ResourcePool',
  'RichTooltip',
  'RigMotionModel',
  'RigidBody',
  'RingBuffer',
  'RoundCounter',
  'RoundLoop',
  'SaveManager',
  'Scheduler',
  'ScopedSaveManager',
  'ScrollView',
  'SegmentedControl',
  'Select',
  'SelectionInfoPanel',
  'SettingsForm',
  'SettingsRow',
  'Sheet',
  'ShopPicker',
  'SidechainDucker',
  'SimulationClock',
  'SkillTree',
  'Slider',
  'SlotContainer',
  'SlotGrid',
  'SoundBank',
  'SoundFamilyBank',
  'SpatialIndex',
  'SplitPane',
  'Spring1D',
  'SquareJoystick',
  'StatBlock',
  'StateMachine',
  'StatsPanel',
  'SwipeGestureZone',
  'SwipeableCardStack',
  'TECH',
  'THEME_IDS',
  'Tabs',
  'Text',
  'TextArea',
  'ThemeController',
  'TimerBar',
  'ToastManager',
  'ToolButton',
  'Toolbar',
  'Tooltip',
  'TouchController',
  'Tree',
  'UIRoot',
  'UI_ALPHA',
  'UI_AUDIO_CHANNELS',
  'UI_AUDIO_STORAGE_KEY',
  'UI_CAPACITY',
  'UI_CRITICAL_DUCK',
  'UI_CRITICAL_EVENTS',
  'UI_CURSORS',
  'UI_DEPTH',
  'UI_INTENT_SOUND',
  'UI_MAX_VARIANTS',
  'UI_MAX_VOICES',
  'UI_MICRO_EVENTS',
  'UI_MICRO_GAP_MS',
  'UI_OUTCOME_SOUND',
  'UI_RATE_JITTER',
  'UI_RATIO',
  'UI_SIZE',
  'UI_SLIDER_RATE_RANGE',
  'UI_SOUND_EVENTS',
  'UI_SOUND_PALETTES',
  'UI_SOUND_PUBLIC_DIR',
  'UI_SOUND_VARIANT_KEYS',
  'UI_THEME_SOUND_PALETTE',
  'UI_THRESHOLD',
  'UI_TIMING',
  'UiHapticProvider',
  'UiIntentBus',
  'UiSoundKit',
  'VIEWPORT_REGISTRY_KEY',
  'VOL_COLORS',
  'VOL_FONTS',
  'VOL_ICONS',
  'Vector2',
  'ViewportManager',
  'VirtualActionSource',
  'VirtualList',
  'VirtualStickSource',
  'WeightedPicker',
  'Wizard',
  'WorldCameraController',
  'XPBar',
  'angleDelta',
  'animateValue',
  'applyVolViewport',
  'applyXPGain',
  'approach',
  'articulateRigDefinition',
  'assembleRig',
  'bresenhamLine',
  'buildRigDefinition',
  'canHover',
  'cancelHaptics',
  'channelGain',
  'circleRectOverlap',
  'circlesOverlap',
  'clamp',
  'clamp01',
  'clampSimulationStep',
  'clearTextEntryModeProbe',
  'computeGamepadInput',
  'computePCInputState',
  'computePartLayout',
  'configureCursorAssets',
  'configureIcons',
  'createContact',
  'createDiagnostics',
  'createIdleActions',
  'createIdleSnapshot',
  'createRandom',
  'createSingleProviderSnapshot',
  'createStatefulRandom',
  'createVolGame',
  'damp',
  'describePCBinding',
  'displayCapabilitiesForSession',
  'distance',
  'distanceSquared',
  'emitUiIntent',
  'findBindingConflicts',
  'findPath',
  'finiteOr',
  'finitePositiveOr',
  'getAppVisibility',
  'getBackHandlerCount',
  'getHapticsCapability',
  'glyphFile',
  'glyphNameForButton',
  'glyphUrl',
  'hasLineOfSight',
  'hasTouchInput',
  'i18n',
  'i18next',
  'inputModeForSession',
  'inverseLerp',
  'isDiagnosticsEnabled',
  'isFiniteNumber',
  'isGamepadInputActive',
  'isGamepadTextEntryActive',
  'isHapticsEnabled',
  'isHapticsSupported',
  'isPCInputActive',
  'isSameBinding',
  'isScopedKey',
  'isTouchPrimary',
  'keyboardKeyFile',
  'lerp',
  'lerpAngle',
  'listFocusable',
  'loadIconSprite',
  'measureSupport',
  'migrateLegacyStore',
  'normalizeUiAudioSettings',
  'observeAppVisibility',
  'observeHapticsCapability',
  'observeWakeGaps',
  'pickDirectionalTarget',
  'planRumblePulses',
  'pointInCircle',
  'pointInRect',
  'poseSourceOf',
  'preloadRigTextures',
  'pushBackHandler',
  'raycastCircles',
  'readStick',
  'rectsOverlap',
  'registerIconSprite',
  'registerTextEntryModeProbe',
  'remap',
  'requestGamepadTextEntry',
  'requestTextEntryForElement',
  'requireFinite',
  'resolveBodyContact',
  'resolveDensityId',
  'resolveGamepadActions',
  'resolveGlyphFamily',
  'resolvePCActions',
  'resolveSkillStates',
  'resolveThemeId',
  'resolveWallContacts',
  'resumeAudioAfterWake',
  'rotateTowards',
  'rtsCursorFor',
  'runButtonClick',
  'samplePose',
  'scopeOfKey',
  'scrollContextAt',
  'seedFromString',
  'segmentCircleEntryT',
  'segmentCircleOverlap',
  'segmentOrientedBoxEntryT',
  'selectGamepad',
  'setHapticsDriver',
  'setHapticsEnabled',
  'setTextEntryModeProbe',
  'setTextEntryProvider',
  'shouldUseTouchControls',
  'showConfirm',
  'showFatalStartupError',
  'solveTwoBoneIk',
  'suppressNativeMenus',
  'triggerBack',
  'uiDuckProfiles',
  'uiIntentBusFor',
  'uiSoundAssets',
  'uiSoundFileStem',
  'uiSoundPaletteFor',
  'validateRigMetadata',
  'valueNoise',
  'vibrate',
  'wrap',
  'wrapAngle',
];

// Asset compiler'lar bu yüzeye GİRMEZ: runtime yalnızca
// üretilmiş asset'leri çalar, üreteni taşımaz.

describe('CORE public API yüzeyi', () => {
  it('dışa açılan İSİMLER birebir sabittir', () => {
    const actual = Object.keys(Core).sort();
    const expected = [...EXPECTED_PUBLIC_SURFACE];

    const added = actual.filter((name) => !expected.includes(name));
    const removed = expected.filter((name) => !actual.includes(name));

    expect(
      { eklenen: added, silinen: removed },
      'Public yüzey DEĞİŞTİ. Eklenen bir isim genişlemedir; silinen bir isim ' +
        'TÜKETİCİYİ KIRAR. İkisi bilinçliyse listeyi güncelle.',
    ).toEqual({ eklenen: [], silinen: [] });
  });

  it('yüzeyde dahili/geçici görünen isim yoktur', () => {
    // Alt çizgiyle başlayan ya da `Internal`/`Temp` gibi bir SEGMENT taşıyan
    // ismin public API'ye çıkması, barrel otomatikliğinin tipik sızıntı biçimi.
    //
    // Eşleşme camelCase SEGMENTİ üzerinden yapılır, ham substring üzerinden
    // değil: düz `/wip/i` taraması `SwipeableCardStack` ve `SwipeGestureZone`
    // isimlerini yakalıyordu ("S-wip-eable"). Bekçinin kendi yanlış pozitifi,
    // koruduğu şeyden daha hızlı devre dışı bırakılır.
    const FORBIDDEN_SEGMENTS = ['internal', 'temp', 'todo', 'wip', 'draft', 'unsafe'];
    const suspicious = Object.keys(Core).filter((name) => {
      if (name.startsWith('_')) return true;
      const segments = name.split(/(?=[A-Z])|[_-]/).map((part) => part.toLowerCase());
      return segments.some((segment) => FORBIDDEN_SEGMENTS.includes(segment));
    });

    expect(suspicious).toEqual([]);
  });

  /*
   * CORE'un adları oyun kelimesi taşımaz: "player" bir oyun kavramıdır,
   * hareket eden şey ise mekanizmadır. `PlayerController` gibi bir takma ad
   * adlandırma sözleşmesini sessizce gevşetir.
   */
  it('oyun kelimesi taşıyan takma ad yüzeye geri GELMEZ', () => {
    expect('PlayerController' in Core).toBe(false);
    expect(Core.MovableController).toBeTypeOf('function');
  });
});
