import type { PresetMetadata } from '../types';

export const ACOUSTIC_CATALOG: Record<string, PresetMetadata> = {
  drawbarOrgan: {
    category: 'instrument',
    role: 'keys',
    genre: 'realistic',
    description: 'Çekmeli org — Hammond ayak oranları, sönümsüz zarf, Leslie kıpırtısı.',
    typicalFrequency: 220,
    typicalDuration: 1.6,
    range: [65.4, 2093],
    useCase: 'Akor yatağı, kilise/gizem teması, sürekli bas altı doku',
    tags: ['keys', 'organ', 'additive', 'sustained'],
    related: ['harpsichord', 'additivePad', 'warmKeys'],
  },
  harpsichord: {
    category: 'instrument',
    role: 'keys',
    genre: 'realistic',
    description: 'Klavsen — parlak koparma spektrumu, 7. harmonikte tarak çukuru, dinamik yok.',
    typicalFrequency: 330,
    typicalDuration: 1.1,
    range: [65.4, 1397],
    useCase: 'Barok tema, saray/entrika sahnesi, ritmik arpej',
    tags: ['keys', 'pluck', 'additive', 'bright'],
    related: ['drawbarOrgan', 'metalPluck', 'woodPluck'],
  },
  marimba: {
    category: 'instrument',
    role: 'bell',
    genre: 'realistic',
    description: 'Marimba — 4:1 akortlu ahşap çubuk, karanlık ve hızlı sönümlü.',
    typicalFrequency: 262,
    typicalDuration: 0.9,
    range: [65.4, 2093],
    useCase: 'Sıcak melodi, oyuncu geri bildirimi, hafif perküsif tema',
    tags: ['mallet', 'wood', 'additive', 'short'],
    related: ['vibraphone', 'glockenspiel', 'woodPluck'],
  },
  vibraphone: {
    category: 'instrument',
    role: 'bell',
    genre: 'realistic',
    description: 'Vibrafon — marimba ile aynı 4:1 akort, metal sönüm, dönen kapak tremolosu.',
    typicalFrequency: 349,
    typicalDuration: 2.4,
    range: [175, 1397],
    useCase: 'Yumuşak melodi, rüya/hatıra sahnesi, caz rengi',
    tags: ['mallet', 'metal', 'tremolo', 'additive'],
    related: ['marimba', 'glockenspiel', 'crystalBell'],
  },
  glockenspiel: {
    category: 'instrument',
    role: 'bell',
    genre: 'realistic',
    description: 'Glockenspiel — oyulmamış çelik çubuk, HARMONİK OLMAYAN 1/2,76/5,40/8,93 modları.',
    typicalFrequency: 1047,
    typicalDuration: 1.5,
    range: [784, 4186],
    useCase: 'Parlak vurgu, ödül/keşif işareti, üst kayıt süsleme',
    tags: ['mallet', 'metal', 'inharmonic', 'bright'],
    related: ['vibraphone', 'crystalBell', 'bell'],
  },
  heavyDrum: {
    category: 'instrument',
    role: 'percussion',
    genre: 'realistic',
    description: 'Ağır davul — düşen perdeli gövde + hızla boğulan vuruş gürültüsü.',
    typicalFrequency: 78,
    typicalDuration: 1.1,
    range: [40, 160],
    useCase: 'Sinematik vuruş, boss adımı, geçiş vurgusu, ağır tempo',
    tags: ['percussion', 'drum', 'membrane', 'low'],
    related: ['marimba', 'mellowKeys'],
  },
  mellowKeys: {
    category: 'instrument',
    role: 'keys',
    genre: 'fantasy',
    description: 'Yumuşak klavye — sinüse yakın spektrum, hafif akortsuzluk, geniş reverb.',
    typicalFrequency: 262,
    typicalDuration: 2.2,
    range: [65.4, 2093],
    useCase: 'Sakin tema, keşif/menü müziği, hüzünlü melodi yatağı',
    tags: ['keys', 'additive', 'soft', 'detuned'],
    related: ['warmKeys', 'electricPiano2', 'vibraphone'],
  },
};
