import type { PresetMetadata } from '../types';

export const INSTRUMENTS_CATALOG: Record<string, PresetMetadata> = {
  subBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'realistic',
    description: 'Subtractive sawtooth/square bass, hafif drive.',
    typicalFrequency: 55,
    typicalDuration: 0.6,
    useCase: 'Warm bass foundation, rock/electronic bass line',
    tags: ['bass', 'subtractive', 'warm'],
    related: ['pluckSubBass', 'dubBass', 'softBass'],
  },
  pluckSubBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'sci-fi',
    description: 'FM perküsif sub bass, kısa atak.',
    typicalFrequency: 55,
    typicalDuration: 0.45,
    useCase: 'Plucky low-end, rhythmic bass',
    tags: ['bass', 'fm', 'pluck'],
    related: ['subBass', 'dubBass'],
  },
  softBass: {
    category: 'instrument',
    role: 'bass',
    genre: 'realistic',
    description: 'Sine + triangle warm sub bass, distortion yok.',
    typicalFrequency: 55,
    typicalDuration: 0.6,
    useCase: 'Warm acoustic-style bass, pastoral themes',
    tags: ['bass', 'subtractive', 'soft'],
    related: ['subBass', 'mossBass'],
  },
  additivePad: {
    category: 'instrument',
    role: 'pad',
    genre: 'fantasy',
    description: 'Additive sine pad — organ/yaylı karakter.',
    typicalFrequency: 220,
    typicalDuration: 2.5,
    useCase: 'Chord backing, warm drone, theme bed',
    tags: ['pad', 'additive', 'warm'],
    related: ['detunedPad', 'warmPad', 'sunlitPad'],
  },
  detunedPad: {
    category: 'instrument',
    role: 'pad',
    genre: 'fantasy',
    description: 'Detune sawtooth pad — geniş ve sürükleyici.',
    typicalFrequency: 220,
    typicalDuration: 2.5,
    useCase: 'Wide synth pad, ambient backing',
    tags: ['pad', 'subtractive', 'wide'],
    related: ['additivePad', 'warmPad'],
  },
  brightLead: {
    category: 'instrument',
    role: 'lead',
    genre: 'sci-fi',
    description: 'Parlak, keskin sawtooth lead.',
    typicalFrequency: 440,
    typicalDuration: 0.7,
    useCase: 'Melodic lead, prominent theme line',
    tags: ['lead', 'subtractive', 'bright'],
    related: ['softLead', 'metalPluck'],
  },
  softLead: {
    category: 'instrument',
    role: 'lead',
    genre: 'fantasy',
    description: 'Yumuşak analog lead — triangle + hafif FM.',
    typicalFrequency: 440,
    typicalDuration: 0.8,
    useCase: 'Gentle melody, solo theme',
    tags: ['lead', 'subtractive', 'soft', 'fm'],
    related: ['brightLead', 'woodPluck'],
  },
  metalPluck: {
    category: 'instrument',
    role: 'pluck',
    genre: 'sci-fi',
    description: 'Metalik pluck — kısa inharmonik FM.',
    typicalFrequency: 660,
    typicalDuration: 0.35,
    useCase: 'Arpeggio, sequencer accent',
    tags: ['pluck', 'fm', 'metallic'],
    related: ['woodPluck', 'metallicClang'],
  },
  woodPluck: {
    category: 'instrument',
    role: 'pluck',
    genre: 'fantasy',
    description: 'Sıcak ahşap pluck — additive harmonikler.',
    typicalFrequency: 440,
    typicalDuration: 0.4,
    useCase: 'Pastoral arpeggio, warm accent',
    tags: ['pluck', 'additive', 'wood'],
    related: ['metalPluck', 'malletPluck'],
  },
  warmKeys: {
    category: 'instrument',
    role: 'keys',
    genre: 'fantasy',
    description: 'Yumuşak keys / Rhodes tan daha az metalik, additive.',
    typicalFrequency: 440,
    typicalDuration: 0.6,
    useCase: 'Soft chord stabs, warm piano alternative',
    tags: ['keys', 'additive', 'warm'],
    related: ['electricPiano', 'electricPiano2'],
  },
  electricPiano2: {
    category: 'instrument',
    role: 'keys',
    genre: 'retro',
    description: 'FM elektrik piyano — daha az gıcık, yumuşak varyant.',
    typicalFrequency: 440,
    typicalDuration: 0.5,
    useCase: 'Rhodes-style stab, chord melody',
    tags: ['keys', 'fm', 'warm'],
    related: ['electricPiano', 'warmKeys'],
  },
  crystalBell: {
    category: 'instrument',
    role: 'bell',
    genre: 'fantasy',
    description: 'Kristal berraklığında çan — additive + FM.',
    typicalFrequency: 880,
    typicalDuration: 1.2,
    useCase: 'Magical bell, high sparkle',
    tags: ['bell', 'additive', 'fm'],
    related: ['bell', 'distantChime'],
  },
};
