import type { PresetMetadata } from '../types';

export const TEXTURES_CATALOG: Record<string, PresetMetadata> = {
  softWind: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Yumuşak, sine-tabanlı rüzgâr / nefes dokusu.',
    typicalFrequency: 400,
    typicalDuration: 3,
    useCase: 'Pastoral ambience background, warm wind bed',
    tags: ['texture', 'pastoral', 'wind', 'pad'],
    related: ['warmPad', 'distantChime'],
  },
  warmPad: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Sıcak organ/yaylı karakterli additive pad.',
    typicalFrequency: 220,
    typicalDuration: 2.5,
    useCase: 'Pastoral chord pad, warm drone, theme background',
    tags: ['texture', 'pastoral', 'pad', 'additive'],
    related: ['softWind', 'malletPluck'],
  },
  machineHum: {
    category: 'texture',
    role: 'texture',
    genre: 'sci-fi',
    description: 'Soğuk, detune sawtooth makine uğultusu.',
    typicalFrequency: 110,
    typicalDuration: 2.5,
    useCase: 'Industrial drone, reactor bed, mechanical ambience',
    tags: ['texture', 'industrial', 'drone', 'machine'],
    related: ['staticField', 'reactorHum'],
  },
  staticField: {
    category: 'texture',
    role: 'texture',
    genre: 'sci-fi',
    description: 'Geniş bant pembe/beyaz gürültü katmanı.',
    typicalFrequency: 2200,
    typicalDuration: 3,
    useCase: 'Industrial noise floor, distant machinery, tension bed',
    tags: ['texture', 'industrial', 'noise', 'static'],
    related: ['machineHum', 'softWind'],
  },
  malletPluck: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Kısa, sıcak mallet / ahşap vuruş dokusu.',
    typicalFrequency: 660,
    typicalDuration: 0.35,
    useCase: 'Pastoral arpeggio, soft accent, warm pluck',
    tags: ['texture', 'pastoral', 'pluck', 'mallet'],
    related: ['warmPad', 'distantChime'],
  },
  distantChime: {
    category: 'texture',
    role: 'texture',
    genre: 'fantasy',
    description: 'Uzak, yumuşak çan vurgusu.',
    typicalFrequency: 880,
    typicalDuration: 2,
    useCase: 'Pastoral bell accent, magical distant chime',
    tags: ['texture', 'pastoral', 'bell', 'chime'],
    related: ['malletPluck', 'warmPad'],
  },
};
